### PR TITLE
Refactoring of APIClient class

### PR DESCRIPTION
**Pull request by sphinks**
Lot of refactoring of ApiClient:
- create separate Utils class for Encoding, Params setting, Extractors
- unit tests for ParamsUtils
- simplify a lot of code with using Apache Commons functions instead of custom created functions
- create an HttpConnectionWrapper for more simple and clear work with HttpConnection: introduced try-with-resources on readers/writers, implemented AutoCloseable
- delete calls of printStackTrace in Exceptions

### CODE REVIEW

**Comment by sphinks** [comment]
@bob983 are you looking after this repo still?

**Comment by bob983** [comment]
Oh my, sorry @sphinks, I lost this PR from my radar, I'm not sure how it happened :(

**Comment by sphinks** [comment]
@bob983 I was thinking that maybe you are on vacation. :)

**Comment by bob983** [comment]
I was actually, but not that long :)

**Comment by sphinks** [comment]
@bob983 any updates on PR? :)

**Comment by bob983** [comment]
Hey, @sphinks, nice work, massive improvement. Thanks for you patience, it took me a while to get to this PR.

**Comment by sphinks** [comment]
@bob983 thanks :)

**Pull request merged**
