### PR TITLE
Encode url params to allow using spaces in values

### PR DESCRIPTION
**Pull request by sphinks**
Fix issue https://github.com/helpscout/helpscout-api-java/issues/23

### CODE REVIEW

**Comment by sphinks** [comment]
Something strange with list of commits in PR, seem like I have done smth wrong. Changes of files are correct!

**Comment by bob983** [comment]
Hi @sphinks, you can do

```
git fetch
git rebase -i remote/develop
git push origin +your_branch_name
```

Please note that `+` means force push.

updated: I assumed you have `helpscout/helpscout-api-java` as `remote` and your fork as `origin`

**Comment by bob983** [comment]
Again, thanks for the PR 😉 From the brief look, I think it needs a test to expose the issue. And I'd probably extracted `URLEncoder.encode(params.get(key), "UTF-8")` to a variable to make it more readable.

The whole method `setParams` is ugly  😞 and needs refactoring, but that's not your fault.

**Comment by sphinks** [comment]
Create another "clean" PR: https://github.com/helpscout/helpscout-api-java/pull/27

**Pull request closed without merging**
